name: Mirror RocketChat

permissions: 
  contents: read
  packages: write
  
on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull from Docker Hub
        run: docker pull registry-1.docker.io/rocketchat/rocket.chat:7.9.7

      - name: Push to GHCR
        run: |
          IMAGE = ghcr.io/${{ github.repository_owner }}/rocket.chat
          docker tag registry-1.docker.io/rocketchat/rocket.chat:7.9.7 $IMAGE:7.9.7
          docker tag registry-1.docker.io/rocketchat/rocket.chat:7.9.7 $IMAGE:latest
          docker push $IMAGE:7.9.7
          docker push $IMAGE:latest

permissions: 
  contents: read
  packages: write
